language: python
dist: trusty
python:
  - "3.5"
  - "3.6"
  - "pypy3"
# command to install dependencies
install:
  - pip install -r test-requirements.txt
  - pip install coveralls==2.0.0
# command to run tests
script:
  - py.test
after_success:
  - coveralls
